### ISSUE TITLE
why are you installing old python manually?

### ISSUE THREAD

**Issue by ZeroChaos-** [r4ulcl/WiFiChallengeLab#1]
https://github.com/RaulCalvoLaorden/WiFiChallengeLab/blob/main/install/installTools.sh#L34

I understand the purpose of installing things from source which are not available as a package, but installing old python manually?  why?

**Comment by r4ulcl** [comment]
Initially I think it was a versioning problem with some software. But it doesn't make any sense now. 
Fixed in commit [af1d5f6](https://github.com/RaulCalvoLaorden/WiFiChallengeLab/commit/af1d5f6b86a227d2a4ea01630b5f2023c43b2d46)
Thanks
