### ISSUE TITLE
use the kali package for hostapd-wpe

### ISSUE THREAD

**Issue by ZeroChaos-** [r4ulcl/WiFiChallengeLab#2]
https://github.com/RaulCalvoLaorden/WiFiChallengeLab/blob/main/install/installTools.sh#L78

why use kali if you don't use the packages it has?

**Comment by r4ulcl** [comment]
The OS of the VM is Debian 11 so that the size was the smallest possible (5GB aprox). In the installer the kali repo  is commented because I tried it and then gave errors, so I installed many of the tools from their GitHub. Also, in most cases it is much more up to date.
Thanks.
