### ISSUE TITLE
last release of vwifi is incompatible with WiFiChallengeLab

### ISSUE THREAD

**Issue by Raizo62** [r4ulcl/WiFiChallengeLab#5]
Hi

Be careful, the last release of vwifi (v6.0) can't use the wlan interfaces added by modprobe.

modprobe must add 0 radios, and you must use the tool **vwifi-add-interfaces** or the parameters "--number" and "--mac" of **vwifi-client** to add the wlan interfaces

But the advantage is that the permanent mac addresses are changed.

**Comment by r4ulcl** [comment]
Thank you so much.

I'm working on a new version of the lab, but thank you very much for the warning, I'll fix it soon.

**Comment by r4ulcl** [comment]
WiFiChallenge v2.0 no longer uses vwifi, but thank you very much for the heads up and the work. 

WiFiChallenge v2.0:
- https://github.com/r4ulcl/WiFiChallengeLab-docker
